config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweeets
  resources :users, except: %i[ show index create new  ]

  get 'users/:username', to: 'users#show', as: :show_user

  get '/404', to: 'errors#not_found', as: :not_found
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweeets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweeets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[ name username ])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /tweeets or /tweeets.json
  def index
    @tweeets = Tweeet.all.order(created_at: :desc)
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = Tweeet.new(body: tweeet_params[:body], user_id: current_user.id)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully created." }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy

    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.where(username: params[:username]).first

    if @user
      render :show, locals: { user: @user }
    else
      redirect_to not_found_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-gray-50'>
    <main class='flex flex-col items-center'>
      <%= yield %>
      <% if user_signed_in? %>
        <%= render partial: 'shared/user_circle' %>
      <% end %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<header class='w-full flex items-center justify-between relative z-50 py-4 px-8 bg-blue-400'>
  <h1 class="font-bold text-2xl text-gray-100">Twittter</h1>
  <%= link_to 'Sign Up', new_user_registration_path, class: "hidden lg:block rounded-lg py-2 px-8 bg-gray-100 font-bold text-blue-400 block font-medium" %>
  <button id="burger" class='text-gray-100 p-1 text-2xl lg:hidden'>☰</button>
  <button id="close-burger" class='hidden'>✕</button>

  <section id="modal-menu"class="hidden">
  <ul class="bg-blue-500 font-bold rounded text-gray-50 shadow-lg w-full flex items-center flex-col absolute top-11">
    <%= link_to 'Register', new_user_registration_path, class: "w-full text-center py-4 border-b" %>
    <li class="w-full text-center py-4 border-b">Tweeet</li>
    <li class="w-full text-center py-4 border-b">Profile</li>
    <li class="w-full text-center py-4">Home</li>
  </ul>
  </section>
</header>

app/views/shared/_user_circle.html.erb
<div class="flex inset-0 z-20 items-end justify-end w-full h-full pointer-events-none fixed bg-transparent">
  <%= button_to destroy_user_session_path, class: 'lg:w-16 lg:h-16 pointer-events-auto w-12 h-12 m-4 rounded-full bg-blue-800', method: :delete do %>
  <% end %>
</div>

app/views/tweeets/_form.html.erb
<%= form_with(model: tweeet, class: "border-0 border-b pb-2 relative z-10") do |form| %>
  <% if tweeet.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
        <% tweeet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_area :body, rows: 4, maxlength: 140, placeholder: "What is happening?", class: "focus:outline-none outline-none text-xl bg-gray-50 block border-0 outline-none border-gray-300 px-6 py-2 w-full resize-none" %>
  </div>

  <div class="inline">
    <%= form.submit 'Tweeet it', class: "text-lg mt-4 rounded-lg py-3 px-6 text-blue-500 font-bold inline-block cursor-pointer" %>
  </div>
<% end %>

app/views/tweeets/_tweeet.html.erb
<div id="<%= dom_id tweeet %>" class='px-8 relative z-10'>
  <p>
    <div class='flex items-center gap-2'>
      <strong class="block text-gray-800 text-xl font-medium"><%= tweeet.user.name %></strong>
      <span class="text-gray-500">@<%= tweeet.user.username %></span>
    </div>
    <%= tweeet.body %>
  </p>

  <% if action_name != "show" %>
  <div id="user-controls" class="flex gap-8 mt-4">
    <%= link_to root_path do %>
      <%= image_tag 'comment.svg' %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/tweeets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing tweeet</h1>

  <%= render "form", tweeet: @tweeet %>

  <%= link_to "Show this tweeet", @tweeet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to tweeets", tweeets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tweeets/index.html.erb
<%= render partial: 'shared/header' %>
  <section class='w-full md:max-w-lg lg:max-w-2xl'>
    </div>
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render partial: 'form', locals: { tweeet: @tweeet } %>

    <div id="tweeets" class='mt-7 relative z-10'>
    <% if @tweeets.any? %>
      <% @tweeets.each do |tweeet| %>
      <%= render tweeet %>
        <div style='height: 1px;' class='bg-gray-300 my-4'></div>
      <% end %>
    <% end %>
    </div>
  </section>

app/views/tweeets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New tweeet</h1>

  <%= render "form", tweeet: @tweeet %>

  <%= link_to 'Back to tweeets', tweeets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tweeets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @tweeet %>

    <%= link_to 'Edit this tweeet', edit_tweeet_path(@tweeet), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this tweeet', tweeet_path(@tweeet), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to tweeets', tweeets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: 'shared/header' %>
<section class="w-full flex flex-col items-center">
  <div class="mt-12 rounded-full w-24 h-24 bg-blue-500 block">
  </div>

  <article class="flex flex-col items-center pb-8 mt-6 border-b w-full">
    <h1 class="font-medium text-2xl text-gray-900"><%= user.name  %></h1>
    <h2 class="text-gray-500">@<%= user.username  %></h2>
  </article>

  <% if user.tweeets.any?  %>
    <% user.tweeets.each do |tweeet|  %>
      <article class="w-full py-8 border-y">
      <%= render partial: 'tweeets/tweeet', locals: { tweeet: tweeet  }  %>
      </article>
    <% end  %>
  <% end %>
</section>